# Generated by Django 4.1.2 on 2023-07-18 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("author", models.CharField(default="", max_length=200)),
                ("year", models.CharField(default="", max_length=10)),
                ("status", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "app_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.appuser",
                    ),
                ),
            ],
        ),
    ]
